"""empty message

Revision ID: 445894356b6d
Revises: None
Create Date: 2016-04-01 22:56:58.327943

"""

# revision identifiers, used by Alembic.
revision = '445894356b6d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    op.drop_column('user', 'last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    ### end Alembic commands ###
