"""empty message

Revision ID: 58019e5d1bc3
Revises: 445894356b6d
Create Date: 2016-04-02 02:58:23.094814

"""

# revision identifiers, used by Alembic.
revision = '58019e5d1bc3'
down_revision = '445894356b6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('thumbnail', sa.String(length=100), nullable=True))
    op.add_column('wishlist', sa.Column('wishlist_id', sa.Integer(), nullable=False))
    op.drop_column('wishlist', 'img_url')
    op.drop_column('wishlist', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('wishlist', sa.Column('img_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('wishlist', 'wishlist_id')
    op.drop_column('wishlist', 'thumbnail')
    ### end Alembic commands ###
